env:
  global:
    - VERSION=0.${TRAVIS_BUILD_NUMBER}
    - DOCKER_HUB_USER=vfarcic

sudo: required

services:
  - docker

script:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -v go:/go -v /var/run/docker.sock:/var/run/docker.sock vfarcic/docker-flow-cron-test bash -c "go get -d -v -t && go test --cover ./... -p=1 && go build -v -o docker-flow-cron"
  - docker build -t vfarcic/docker-flow-cron .
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag vfarcic/docker-flow-cron vfarcic/docker-flow-cron:${VERSION}
  - docker push vfarcic/docker-flow-cron:${VERSION}
  - docker push vfarcic/docker-flow-cron

branches:
  only:
    - master
