env:
  global:
    - VERSION=0.${TRAVIS_BUILD_NUMBER}
    - DOCKER_HUB_USER=vfarcic

sudo: required

services:
  - docker

script:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -v go:/go -v /var/run/docker.sock:/var/run/docker.sock vfarcic/docker-flow-cron-test bash -c "go get -d -v -t && go test --cover ./... -p=1 && go build -v -o docker-flow-cron"
  - docker build -t vfarcic/docker-flow-cron .
  - docker tag vfarcic/docker-flow-cron vfarcic/docker-flow-cron:${VERSION}
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; docker push vfarcic/docker-flow-cron:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; docker push vfarcic/docker-flow-cron; fi'
  - docker-compose -f docker-compose-test.yml run --rm docs
  - docker build -t vfarcic/docker-flow-proxy-docs -f Dockerfile.docs .
  - docker tag vfarcic/docker-flow-proxy-docs vfarcic/docker-flow-proxy-docs:${VERSION}
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-proxy-docs:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-proxy-docs; fi'

branches:
  only:
    - master
