version: '2'


services:

  unit:
    image: golang:1.6
    volumes:
      - .:/usr/src/myapp
      - /tmp/go:/go
    working_dir: /usr/src/myapp
    command: sh -c "go get -d -v -t && go test --cover ./... --run UnitTest && go build -v -o docker-flow-cron"
