version: '2'


services:

  unit:
    image: vfarcic/docker-flow-cron-test
    volumes:
      - .:/usr/src/myapp
      - ./go:/go
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/src/myapp
    command: bash -c "go get -d -v -t && go test --cover ./... -p=1 && go build -v -o docker-flow-cron"
